libcamera: add missing <stdint.h> include to base/file.h
Without the change the build fails on upcoming `gcc-15` as:

    In file included from ../src/libcamera/base/file.cpp:8:
    ../include/libcamera/base/file.h:62:33: error: 'uint8_t' was not declared in this scope
       62 |         ssize_t read(const Span<uint8_t> &data);
          |                                 ^~~~~~~

Signed-off-by: Sergei Trofimovich <slyich@gmail.com>
Signed-off-by: Kieran Bingham <kieran.bingham@ideasonboard.com>