libcamera: add missing <stdint.h> include to internal/yaml_parser.h
Without the change the build fails on upcoming `gcc-15` as:

    In file included from ../src/libcamera/yaml_parser.cpp:8:
    ../include/libcamera/internal/yaml_parser.h:183:41: error: 'uint8_t' was not declared in this scope
      183 |                          std::is_same_v<uint8_t, T> ||
          |                                         ^~~~~~~

Signed-off-by: Sergei Trofimovich <slyich@gmail.com>
Signed-off-by: Kieran Bingham <kieran.bingham@ideasonboard.com>