backtracre: Include cxxabi.h without HAVE_DW
Since its used in code without HAVE_DW, it fails to compile on such
systems e.g. linux/musl

Fixes
src/libcamera/base/backtrace.cpp:235:16: error: use of undeclared identifier 'abi'
                char *name = abi::__cxa_demangle(symbol, nullptr, nullptr, nullptr);
                             ^
1 error generated.

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Kieran Bingham <kieran.bingham@ideasonboard.com>